// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-jFemtkwI6Sqd_KLkqPo87sZR6BigAWY',
    appId: '1:313368853530:web:335d3a55a87e5b3fa5a5a3',
    messagingSenderId: '313368853530',
    projectId: 'appfactory-5efd9',
    authDomain: 'appfactory-5efd9.firebaseapp.com',
    databaseURL: 'https://appfactory-5efd9-default-rtdb.firebaseio.com',
    storageBucket: 'appfactory-5efd9.firebasestorage.app',
    measurementId: 'G-D8ET4THZSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAThPOLclkPAFXYM3vuehLcc_UeU5ve5E0',
    appId: '1:313368853530:android:3161fe69755a870ea5a5a3',
    messagingSenderId: '313368853530',
    projectId: 'appfactory-5efd9',
    databaseURL: 'https://appfactory-5efd9-default-rtdb.firebaseio.com',
    storageBucket: 'appfactory-5efd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULf5pDxEwyWEllyEXM1zu6KxUpGDtjRM',
    appId: '1:313368853530:ios:3fc12869d74c6d78a5a5a3',
    messagingSenderId: '313368853530',
    projectId: 'appfactory-5efd9',
    databaseURL: 'https://appfactory-5efd9-default-rtdb.firebaseio.com',
    storageBucket: 'appfactory-5efd9.firebasestorage.app',
    iosBundleId: 'com.example.appfactorytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULf5pDxEwyWEllyEXM1zu6KxUpGDtjRM',
    appId: '1:313368853530:ios:3fc12869d74c6d78a5a5a3',
    messagingSenderId: '313368853530',
    projectId: 'appfactory-5efd9',
    databaseURL: 'https://appfactory-5efd9-default-rtdb.firebaseio.com',
    storageBucket: 'appfactory-5efd9.firebasestorage.app',
    iosBundleId: 'com.example.appfactorytest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-jFemtkwI6Sqd_KLkqPo87sZR6BigAWY',
    appId: '1:313368853530:web:f49b35fe2f53d636a5a5a3',
    messagingSenderId: '313368853530',
    projectId: 'appfactory-5efd9',
    authDomain: 'appfactory-5efd9.firebaseapp.com',
    databaseURL: 'https://appfactory-5efd9-default-rtdb.firebaseio.com',
    storageBucket: 'appfactory-5efd9.firebasestorage.app',
    measurementId: 'G-KESX7JC9GY',
  );
}
